SELECT 
    COUNT(*) as COUNT
FROM 
    (SELECT
        (CASE WHEN GENOTYPE % 2 = 1 THEN 1 ELSE 0 END) as TYPE1,
        (CASE WHEN GENOTYPE DIV 2 % 2 = 1 THEN 1 ELSE 0 END) as TYPE2,
        (CASE WHEN GENOTYPE DIV 2 DIV 2 % 2 = 1 THEN 1 ELSE 0 END) as TYPE3,
        (CASE WHEN GENOTYPE DIV 2 DIV 2 DIV 2 % 2 = 1 THEN 1 ELSE 0 END) as TYPE4
    FROM ECOLI_DATA) AS SUB
WHERE TYPE2 = 0 and (TYPE1 = 1 OR TYPE3 = 1);